### ISSUE TITLE
[BUG] Different services displayed depending if the project is running or stopped

### ISSUE THREAD

**Issue by biati-digital** [biati-digital/vscode-ddev-manager#9]
**Describe the bug**
Doing `ddev describe -j` on a running project outputs the services (included by default or installed by the user), but when the project is not running `ddev describe -j` returns the services empty `"services": {},"`

What's a reliable way to get all the services even if the project is not running?

**To Reproduce**
Install a custom service, it will only be displayed in the sidebar when the project is running.

**Expected behavior**
It would be great to be able to display the installed services even if the project is not running, I do not need url's or ports (because it's not running), just the service name/short_name

**Screenshots**

When running
![CleanShot 2023-09-12 at 21 55 08](https://github.com/biati-digital/vscode-ddev-manager/assets/1219228/0882b786-ec2c-48a6-9ca4-b9ef0663d526)

When stopped
![CleanShot 2023-09-12 at 21 55 46](https://github.com/biati-digital/vscode-ddev-manager/assets/1219228/006c4149-3649-4a9d-840f-ad4366492db4)

**System (please complete the following information):**

- OS: macOS Ventura
- DDEV version: v1.22.1
- Docker provider: Orbstack
- VSCode version: v1.82.0
- DDEV Manager version: 1.1.1

**Comment by tyler36** [comment]
For things like PHP, Node, and databases, versions and types are usually stored in `.ddev/config.yml`
(Should the database be one level higher?)

You could also use (or compare) the output from `.ddev/add-metadata/name/manifest.yaml` with the `ddev describe -j`'s services. This would only work with addons installed via `ddev get`, and _not_ manually added files.

**Comment by biati-digital** [comment]
PHP, Node and db is returned correctly, it's just for services/addons installed with `ddev get`. I think I can use the manifest.yaml inside addon-metadata when the project is not running. Just one doubt.

Can I assume that the service short name is just the addon name without ddev-? for example:

This is the content of `.ddev/addon-metadata/ddev-buggregator/manifest.yaml`

```
name: ddev-buggregator
repository: iljapolanskis/ddev-buggregator
version: 1.0.0
install_date: "2023-09-10T14:50:15-06:00"
project_files:
    - docker-compose.buggregator.yaml
global_files: []
removal_actions: []
```

and this is the content of `docker-compose.buggregator.yaml`

```
#ddev-generated
# Buggregator Server
services:
  buggregator:
    container_name: ddev-${DDEV_SITENAME}-buggregator
    hostname: ${DDEV_SITENAME}-buggregator
    image: ghcr.io/buggregator/server:latest
    expose:
      - "8000"
      - "1025"
      - "9912"
      - "9913"
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTPS_EXPOSE=8000:8000,1025:1025,9912:9912,9913:9913
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"

```

There is no place where the add-on defines just `buggregator`. Doing `ddev describe -j` on a running project outputs this:

![CleanShot 2023-09-12 at 22 27 08](https://github.com/biati-digital/vscode-ddev-manager/assets/1219228/128799b8-6e69-4e41-a4d5-68d37017aa88)

I'm currently using the shortname so I need to know if I can simply remove ddev- from the name defined in manifest.yaml so I get the same shortname that ddev returns when the project is running.
